[package]
name = "data-dandy"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
eframe = "0.31.1"
egui = "0.31.1"
plotters = "0.3.7"
polars = "0.49.1"
reqwest = { version = "0.12.20", features = ["blocking"] }
serde = "1.0.219"
serde_json = "1.0.140"
tokio = "1.45.1"
